### ISSUE TITLE
Remove any traces of private randomness

### ISSUE THREAD

**Issue by AnomalRoil** [drand/drand#1064] opened 2022-09-13 13:43 UTC
Drand is really about public distributed randomness, so we are not supporting private randomness anymore.

We should make sure the code is cleanup and doesn't contain private randomness stuff anymore and that the doc (in the drand website repo) isn't referring to it anymore.

**Comment by aswin2108** [comment] 2022-09-14 09:11
I am really interested in doing this. Could you please assign this to me? I would really love to do this as a part of hacktoberfest.

**Comment by CluEleSsUK** [comment] 2022-09-14 09:15
Done! Thanks for the help

**Comment by AnomalRoil** [comment] 2022-09-14 09:39
For instance, this and other related code (dedicated protobuf, etc.) should go:
https://github.com/drand/drand/blob/5c6199bb1b675c72d53ee1e501823a1264eb2a63/core/drand_beacon_public.go#L134-L159

**Comment by aswin2108** [comment] 2022-09-14 10:08
@AnomalRoil  Okay, thanks for the heads up. Will keep it in mind!

**Comment by aswin2108** [comment] 2022-09-25 13:02
I am having this issue while running `make demo`
`panic: exec: "drand": executable file not found in $PATH`
To solve that I tried to follow: https://go.dev/doc/code#GOPATH
I did `go mod init` output was `it already exists` 
 Can anyone guide me in this!?

**Comment by AnomalRoil** [comment] 2022-09-27 20:57
That's probably because the `make demo` isn't using the relative path properly.

Try instead to do:
```
$ go build
$ go test -race ./...
```

This will complain if it cannot build it and then running the main tests should complain if something doesn't work as expected.

**Comment by aswin2108** [comment] 2022-10-01 13:32
@AnomalRoil really sorry for the late reply! It's failing. This is the output:
![image](https://user-images.githubusercontent.com/72661784/193411969-14173556-6a6a-4376-a670-fff3ea50e833.png)

**Comment by aswin2108** [comment] 2022-10-06 06:37
Really sorry, I am not able to do it!

**Comment by AnomalRoil** [comment] 2022-10-06 14:00
No worries. It's weird it's not working on your machine. Are you running Go 1.18 ?

**Comment by aswin2108** [comment] 2022-10-06 18:06
nope! Go 1.19

**Comment by Bexanderthebex** [comment] 2022-10-14 07:26
@AnomalRoil hi! I am interested in taking this on if you guys don't mind :)

**Comment by AnomalRoil** [comment] 2022-10-17 10:09
@Bexanderthebex  Sure, please go ahead 👍🏻

**Comment by Bexanderthebex** [comment] 2022-10-21 06:30
@AnomalRoil just want to see what would the roll-out look like? Is this by design that this gets into the next major release? Or should we allow them to have flags to enable private randomness (disabled by default) and then just have it removed after the initial communication that this will get deprecated. Again, fairly new with the project.

**Comment by AnomalRoil** [comment] 2022-10-21 11:25
Currently private randomness doesn't even work on the League of Entropy because we're not exposing it (it's currently behind a flag), so we would just drop it completely in v1.5.0 or maybe in v2.0.0, with a big warning in the release notes. But as far as I know, drand is only used by the League of Entropy to run its networks and maybe by a few private networks, but they would probably be using their own distributed public randomness and not the private one.

**Comment by Bexanderthebex** [comment] 2022-10-21 13:01
Got it, thank you for the clarification, I can start working on it then.

**Comment by Bexanderthebex** [comment] 2022-10-26 05:54
@AnomalRoil I opened a PR to address this, would you mind checking when you have time?

**Closed** 2022-10-26 12:54 UTC
Labels: good first issue, refactoring, hacktoberfest, docs
