### ISSUE TITLE
Put a domain separation tag for the partial signature and final randomness

### ISSUE THREAD

**Issue by nikkolasg** [drand/drand#196] opened 2020-02-07 17:37 UTC

**Comment by alanshaw** [comment] 2020-05-11 09:53
@nikkolasg is this a dupe of https://github.com/drand/drand/issues/254?

**Comment by nikkolasg** [comment] 2020-05-11 10:21
Nope the issues expose the same problem but in two different places. Could be merged if we wanted to.

**Closed** 2024-07-09 11:48 UTC
