### ISSUE TITLE
Upload of image to Docker Hub from Travis CI fails

### ISSUE THREAD

**Issue by sbellem** [drand/drand#201] opened 2020-02-24 21:32 UTC
The Travis CI config contains instructions to upload the image to Docker Hub but **push** access appears to be [denied](https://travis-ci.org/drand/drand/builds/652118643#L7054):

```shell
denied: requested access to the resource is denied
```

Please let me know if I can help in fixing this! :smile:

**Comment by nikkolasg** [comment] 2020-02-24 23:12
Mhhh right, good find !

I think the issue is that I'm not in the dedis org anymore, and drand has moved away from the dedis repo. So we would need create a drand org on dockerhub, give access to me and some other contributors and push the docker image there.

Yeah for sure, if you can help with that, that's most welcomed !

**Comment by sbellem** [comment] 2020-02-25 22:10
> Yeah for sure, if you can help with that, that's most welcomed !

Ok great I'll take care of it!

**Comment by sbellem** [comment] 2020-02-26 03:57
The **drand** org namespace is already taken: https://hub.docker.com/u/drand

**Comment by nikkolasg** [comment] 2020-02-26 12:04
Damn :D 
drand-project , drand-org ? anything sensible with drand inside is good to me !

**Comment by nikkolasg** [comment] 2020-05-04 22:06
Thankfully we dont use travis anymore so closing.

**Closed by nikkolasg** 2020-05-04 22:06 UTC
