### ISSUE TITLE
Round 1 doesn't display correctly

### ISSUE THREAD

**Issue by ltv511** [drand/drand#372] opened 2020-05-21 13:50 UTC
The first round is not returned correctly by the server. For example, https://drand.cloudflare.com/public/1  hangs but https://drand.cloudflare.com/public/2 successfully returns the round.

Perhaps because the first round has no previous_signature?

**Comment by hsanjuan** [comment] 2020-05-22 08:52
I confirm this. Only happens with the http api exposed by the drand node, not with the http relay though.

**Comment by willscott** [comment] 2020-05-22 15:37
Should be fixed as a side cleanup in #377

**Comment by willscott** [comment] 2020-05-26 15:12
root cause fixed in #393

**Closed by willscott** 2020-05-26 15:12 UTC
Labels: kind/bug
